import jwt, { SignOptions } from "jsonwebtoken";
import { env } from "@/config/env";
import type { AccessTokenPayload, RefreshTokenPayload } from "@/types/jwt.types";

/**
 * Parses simple duration strings like "15m", "7d", "60s", "2h" into
 * milliseconds. Hand-rolled instead of pulling in the `ms` package —
 * jsonwebtoken depends on `ms` internally for its own `expiresIn` option,
 * but doesn't export it, and this app only ever needs a handful of unit
 * suffixes for computing cookie `maxAge` / DB `expiresAt` values.
 */
export function parseDurationToMs(duration: string): number {
  const match = /^(\d+)\s*(ms|s|m|h|d)$/.exec(duration.trim());
  if (!match) {
    throw new Error(`Invalid duration string: "${duration}". Expected e.g. "15m", "7d".`);
  }
  const value = Number(match[1]);
  const unit = match[2] as "ms" | "s" | "m" | "h" | "d";
  const unitMs: Record<typeof unit, number> = {
    ms: 1,
    s: 1_000,
    m: 60_000,
    h: 3_600_000,
    d: 86_400_000,
  };
  return value * unitMs[unit];
}

export const ACCESS_TOKEN_MAX_AGE_MS = parseDurationToMs(env.JWT_ACCESS_EXPIRES_IN);
export const REFRESH_TOKEN_MAX_AGE_MS = parseDurationToMs(env.JWT_REFRESH_EXPIRES_IN);

/**
 * Access and refresh tokens are signed with SEPARATE secrets
 * (JWT_ACCESS_SECRET / JWT_REFRESH_SECRET). Access tokens are verified on
 * every authenticated request and therefore appear far more often in logs,
 * error traces, and memory — keeping the two secrets independent means a
 * leak of one does not let an attacker forge the other token type.
 */

export function signAccessToken(payload: AccessTokenPayload): string {
  return jwt.sign(payload, env.JWT_ACCESS_SECRET, {
    expiresIn: env.JWT_ACCESS_EXPIRES_IN,
  } as SignOptions);
}

export function verifyAccessToken(token: string): AccessTokenPayload {
  return jwt.verify(token, env.JWT_ACCESS_SECRET) as AccessTokenPayload;
}

/**
 * `payload` MUST already contain a `jti` — generated by the caller
 * (token.service.ts, via crypto.randomUUID()) so the exact same value can
 * be persisted as RefreshToken.jti in the same operation that mints the
 * token. jwt.ts itself stays Prisma-agnostic and just signs whatever
 * payload it's given.
 */
export function signRefreshToken(payload: RefreshTokenPayload): string {
  return jwt.sign(payload, env.JWT_REFRESH_SECRET, {
    expiresIn: env.JWT_REFRESH_EXPIRES_IN,
  } as SignOptions);
}

export function verifyRefreshToken(token: string): RefreshTokenPayload {
  return jwt.verify(token, env.JWT_REFRESH_SECRET) as RefreshTokenPayload;
}
